# Generated by Django 4.1.7 on 2023-07-01 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('exam_name', models.CharField(max_length=100, unique=True)),
                ('instruction', models.TextField()),
                ('duration_of_exam', models.DurationField()),
                ('total_marks', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('slug_exam', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=50, unique=True)),
                ('slug_question_type', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Numericals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField(unique=True)),
                ('question', models.TextField(max_length=500, null=True)),
                ('question_image', models.ImageField(null=True, upload_to='images/')),
                ('ans_min_range', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ans_max_range', models.DecimalField(decimal_places=2, max_digits=6)),
                ('answer', models.DecimalField(decimal_places=2, max_digits=6)),
                ('slug_numericals', models.SlugField()),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numericals', to='exam.exam')),
                ('question_type', models.ForeignKey(default='Numericals', on_delete=django.db.models.deletion.SET_DEFAULT, to='exam.questiontype')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField(unique=True)),
                ('question', models.TextField(max_length=500, null=True)),
                ('question_image', models.ImageField(null=True, upload_to='images/')),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('marks', models.PositiveIntegerField(default=0)),
                ('answer', models.CharField(choices=[('A', 'option1'), ('B', 'option2'), ('C', 'option3'), ('D', 'option4')], max_length=1)),
                ('slug_multiplechoice', models.SlugField()),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiplechoice', to='exam.exam')),
                ('question_type', models.ForeignKey(default='MultipleChoice', on_delete=django.db.models.deletion.SET_DEFAULT, to='exam.questiontype')),
            ],
        ),
    ]
