# Generated by Django 4.1.7 on 2023-07-01 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiSelect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('question_no', models.IntegerField(unique=True)),
                ('question', models.TextField(max_length=500, null=True)),
                ('question_image', models.ImageField(null=True, upload_to='images/')),
                ('marks', models.PositiveIntegerField(default=0)),
                ('slug_multiselect', models.SlugField()),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiselect', to='exam.exam')),
                ('question_type', models.ForeignKey(default='Multiselect', on_delete=django.db.models.deletion.SET_DEFAULT, to='exam.questiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('option_no', models.PositiveIntegerField(unique=True)),
                ('options', models.CharField(max_length=100)),
                ('is_answer', models.BooleanField(default=False)),
                ('slug_options', models.SlugField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exam.multiselect')),
            ],
        ),
    ]
