# Generated by Django 4.1.7 on 2023-07-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_exam_access_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration_of_exam',
            field=models.DurationField(help_text='Enter the duration in the format "HH:MM:SS"'),
        ),
    ]
