# Generated by Django 4.1.7 on 2023-07-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_exam_duration_of_exam_alter_exam_slug_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
