# Generated by Django 4.1.7 on 2023-07-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_alter_exam_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_id',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
