# Generated by Django 4.1.7 on 2023-07-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_alter_exam_exam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Make Sure to Set Active-state while creating.'),
        ),
    ]
