# Generated by Django 4.1.7 on 2023-07-03 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0010_remove_regularusermodel_purchased_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_purchased', models.BooleanField(blank=True)),
                ('video_purchased', models.BooleanField(blank=True)),
                ('exam_purchased', models.BooleanField(blank=True)),
                ('duration', models.IntegerField(blank=True)),
                ('purchased_date', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateTimeField(blank=True)),
                ('purhcased_course', models.ManyToManyField(blank=True, to='user.fieldofstudy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasedcourses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
