# Generated by Django 4.1.7 on 2023-07-29 17:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('regularuserview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchase', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateTimeField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasedate', to='regularuserview.userprofile')),
            ],
        ),
    ]
