# Generated by Django 4.1.7 on 2023-07-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_chapters_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofstudy',
            name='Course_description',
            field=models.TextField(default='course Description'),
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='user_benefit',
            field=models.TextField(default='user benefits', help_text="Enter what the user's benefit with the course."),
        ),
    ]
