# Generated by Django 4.1.7 on 2023-07-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_fieldofstudy_course_description_fieldofstudy_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Make Sure to Set Active-state while creating.'),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Make Sure to Set Active-state while creating.'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Make Sure to Set Active-state while creating.'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Make Sure to Set Active-state while creating.'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='Make Sure to Set Active-state while creating.'),
        ),
    ]
