# Generated by Django 4.1.7 on 2023-07-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_chapters_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularusermodel',
            name='purchased_courses',
            field=models.ManyToManyField(blank=True, to='user.fieldofstudy'),
        ),
    ]
