# Generated by Django 4.1.7 on 2023-07-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_regularusermodel_purchased_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_purchased', models.BooleanField(blank=True)),
                ('video_purchased', models.BooleanField(blank=True)),
                ('exam_purchased', models.BooleanField(blank=True)),
                ('duration', models.IntegerField(blank=True)),
                ('purchased_date', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateTimeField(blank=True)),
                ('slug_purchasedcourse', models.SlugField(blank=True, unique=True)),
                ('purhcased_course', models.ManyToManyField(blank=True, to='user.fieldofstudy')),
            ],
        ),
        migrations.AddField(
            model_name='regularusermodel',
            name='purhcased_course',
            field=models.ManyToManyField(blank=True, to='user.purchasedcourses'),
        ),
    ]
