# Generated by Django 4.1.7 on 2023-07-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_purchasedcourses_slug_purchasedcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedcourses',
            name='slug_purchasecustom',
            field=models.SlugField(blank=True),
        ),
    ]
