# Generated by Django 4.1.7 on 2023-07-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_purchasedcourses_slug_purchasecustom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedcourses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
