# Generated by Django 4.1.7 on 2023-07-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_purchasedcourses_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedcourses',
            name='slug_purchasecustom',
        ),
    ]
