# Generated by Django 4.1.7 on 2023-07-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_purchasedcourses_slug_purchasecustom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedcourses',
            name='expires_on',
        ),
    ]
