# Generated by Django 4.1.7 on 2023-07-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_purchasedcourses_expires_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularusermodel',
            name='purhcased_course',
            field=models.ManyToManyField(blank=True, to='user.fieldofstudy'),
        ),
        migrations.DeleteModel(
            name='PurchasedCourses',
        ),
    ]
