# Generated by Django 4.1.7 on 2023-07-04 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_regularusermodel_purhcased_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamsNested',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('exam_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=600)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('slug_exams', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Make Sure to Set Active-state while creating.')),
                ('access_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.access_type')),
            ],
        ),
        migrations.CreateModel(
            name='NotesNested',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=600)),
                ('pdf_link', models.URLField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('slug_notes', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Make Sure to Set Active-state while creating.')),
                ('access_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.access_type')),
            ],
        ),
        migrations.CreateModel(
            name='videosNested',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=600)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('slug_videos', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Make Sure to Set Active-state while creating.')),
                ('access_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.access_type')),
            ],
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Chapters',
        ),
        migrations.DeleteModel(
            name='ChapterType',
        ),
        migrations.AddField(
            model_name='videosnested',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='user.modules'),
        ),
        migrations.AddField(
            model_name='notesnested',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='user.modules'),
        ),
        migrations.AddField(
            model_name='examsnested',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='user.modules'),
        ),
    ]
